services:
  postgres:
    image: postgres:16-alpine
    container_name: bay-postgres
    environment:
      POSTGRES_USER: bay_user
      POSTGRES_PASSWORD: bay_password
      POSTGRES_DB: betting_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U bay_user -d betting_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
